# Generated by Django 3.1.1 on 2020-10-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_url', models.URLField(blank=True, max_length=250, null=True)),
                ('has_url', models.BooleanField(default=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('freq_num', models.IntegerField(default=3)),
                ('rand_video', models.BooleanField(default=False)),
            ],
        ),
    ]
