# Generated by Django 3.0.10 on 2020-10-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lofi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='userinput',
            name='article_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
